# Profile section
profile:
  first_name: Pavan Kumar
  last_name: PHV
  picture: static/img/pavankumar.JPG  # Local picture
  # picture: static/img/rodo_2021.png  # Local picture
  contact:
    address_one: Banglore
    phone: +91-9912552285
  email: phvpavankumar@gmail.com
  description: |
    I am a AI Engineer at IGNIRAIUM. (INDIA) and I also collaborate as a AI Consultant for the Sony Banglore.
    
    I've worked as a Python Dev at Amrita School of Engineering and served as a research assistant in applied AI at the AI Research Center, part of the Amrita Vishwa Vidhyapeetam in Coimbatore. 
    
    I am (currently) a Sony AI Consultatnt Expert in Machine Learning.


# Social section
social:
  website: https://pavan-kumar.glitch.me/
  github: https://github.com/phvpavankumar
  # twitter: https://twitter.com/rodo_ferro/
  linkedin: https://www.linkedin.com/in/pavan-kumar-phv/
  # facebook:
  # dev: https://dev.to/rodolfoferro
  # medium: https://medium.com/@FerroRodolfo


# Experience section
experience:
  item3:
    position: AI Consultant
    company: SONY INDIA Pvt Ltd
    from: Feb 2023 
    to: Present
    description: >
      Working as an AI consultant for Sony Group Corporation, commonly known as simply Sony (stylized as SONY), is a Japanese multinational conglomerate corporation headquartered in Minato, Tokyo, Japan. Company focused on largest manufacturer of image sensors, the second largest camera manufacturer, and is among the semiconductor sales leaders.
    link: https://www.sony.co.in/homepage
  item2:
    position: AI Engineer
    company: IGNITARIUM Pvt Ltd
    from: Aug 2021
    to: Jan 2023
    description: >
       AI Engineer in IGINARIUM, contributed with the models developed and the AI pipelines (we develped a Python package for it).
    link: https://ignitarium.com/
  item1:
    position: AI Research Assistant
    company: Amrita School of Engineering
    from: August 2020
    to: August 2022
    description: >
      On charge of doing research and building neural networks for computer vision problems, focused on applications and solutions for real industry issues. Deployed trained models to production.
  reference: https://www.amrita.edu/research/


# Education section
education:
  item1:
    institution: Amrita School of Engineering
    program: Master of Data Science
    description: Persued Post graduation dgree in Data Science, majorly focused on Computer Vision and NLP problems. Published my thesis in Sentiment analysis in dravidian multi lingual languages.
    from: August 2020
    to: August 2022
  item2:
    institution: Amrita School of Engineering
    program: Bachelors in Mechanical Enginering.
    description: Major in Mathematics with Mathematical Computing as terminal area.
    from: August 2015
    to: July 2019


# Community section:
community:
  item0:
    institution: Analytics and Data Science Career
    program: Analytics and Data Science Career Community Builder
    description: "To enhance the importance of Artifical Inteligence collaborated as a Analytics and Data Science Career community builder."
    from: October 2022
    to: Present
    link: https://www.linkedin.com/groups/6744146/
  reference: https://www.linkedin.com/groups/6744146/?highlightedUpdateUrn=urn%3Ali%3AgroupPost%3A6744146-6986234744703258624&q=highlightedFeedForGroups



# Skills section
tools:
  # Consider that the following are fa icons:
  #   https://fontawesome.com/icons?d=gallery&s=brands
  - python
  - markdown
  - github
  - gitlab
  - bitbucket
  - docker
  - microsoft
  - google
  - google-drive
  - slack
  - linux
  - raspberry-pi
  - apple
extra_skills:
  # - Facebook Messenger, Telegram, and SMS bots
  - Python APIs and AI model development.
  - Image processing and computer vision
  - Machine learning and deep learning
  - Several Python packages – OpenCV, NumPy, TensorFlow, Pytorch etc.
  - Expert in deploying AI models in Embedded devices - Raspy, google dev board and Sony's micro controller IMX500. 

# Blogs section
blogs:
  item0:
    name: Solar Panel defect detection
    blog: Solar Panel defect detection using AI techniques for beginers, March 2023.
    material:
    link: https://ignitarium.com/solar-panel-defect-detection-using-ai-techniques/
  item1:
    name: Object detection with yolo-v5
    blog: Developing a AI model having no knowledge in AI domie, October 2022.
    material:
    link: https://www.linkedin.com/posts/pavan-kumar-phv_yolov5-yaml-yolov5x-activity-6986232295217127424-3gC6?utm_source=share&utm_medium=member_desktop
  item2:
    name: GitLab for beginners
    blog: Getting started with GitLab for beginners, August 2021.
    material:
    link: https://ignitarium.com/gitlab-for-beginners/
  item3:
    name: github tutorials for beginners
    blog: Getting started with github for beginers, August 2021.
    material:
    link: https://ignitarium.com/github-for-beginners/
  item4:
    name: git tutorials for beginners. 
    blog: Getting started with git commands for beginers, July 2021.
    material:
    link: https://ignitarium.com/git-commands-for-beginners/
    # reference: https://rodolfoferro.xyz/resume/


# Projects section
projects:
  item1:
    title: flask-portfolio-template
    subtitle: A portfolio template built with Flask.
    description: An easy-to-configure simple resume template built with Flask and Bootstrap.
    link: https://github.com/phvpavankumar/flask-resume-template
    github: https://github.com/phvpavankumar/flask-resume-template
    img: flask-resume-template.png
    tags: [Flask, Python, Bootstrap, CSS, JavaScript]
  item2:
    title: Deep Learning Based Sentiment Analysis for Malayalam, Tamil and Kannada Languages
    subtitle: Natural Language Processing (NLP)
    description: To classify the underlying sentiments of text as positive, negative, mixed feelings, Native, non-Native, I performed sentiment analysis with NLP techniques integrated with different Deep-learning based architectures.
    link: https://github.com/phvpavankumar/Sentiment-Analysis-for-Malayalam-Tamil-and-Kannada-Languages
    github: https://github.com/phvpavankumar/Sentiment-Analysis-for-Malayalam-Tamil-and-Kannada-Languages
    img: Sentiment_analyisis.png
    tags: [Python, NLP, Images, Data Preprocessing, Sentiment analyisis, dravidian languages, Twitter, YouTube, Tamil, Malayalam, Kannada]
  item3:
    title: Automatic Plant Watering System
    subtitle: A Automatic Plant Watering System prototype pipeline created to support the irrigation system.
    description: Basically to automate the irrigation, I  developed a  automate water monitoring system which will automate the irrigation system in the absence of human being also.
    link: hhttps://github.com/phvpavankumar/Automatic-Plant-Watering-System
    github: https://github.com/phvpavankumar/Automatic-Plant-Watering-System
    img: Automatic_Plant_Watering_System.png
    tags: [C++, Embedded systems, Moisture sensors, Adruino UNO]
  item4:
    title: Convex Optimization of Image Denoising using CVXPY layers
    subtitle: Image Denoising using CVXPY layers
    description: The primary objective is to analyze the performance of Convex Optimization CVXPY layers solver in modified VGG-16 Net for Image Classification of Noisy MNIST dataset.
    link: https://github.com/phvpavankumar/Convex-Optimization-of-Image-Denoising-using-CVXPY-layers
    github: https://github.com/phvpavankumar/Convex-Optimization-of-Image-Denoising-using-CVXPY-layers
    img: cvxpy_denoising.png
    tags: [Python, Computer Vision, Keras, Neural Networks, cvxpy, denoising, MNIST dataset, VGG16]

